// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EntUsersColumns holds the columns for the "entUsers" table.
	EntUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "sex", Type: field.TypeBool, Nullable: true},
		{Name: "address", Type: field.TypeString},
	}
	// EntUsersTable holds the schema information for the "entUsers" table.
	EntUsersTable = &schema.Table{
		Name:        "entUsers",
		Columns:     EntUsersColumns,
		PrimaryKey:  []*schema.Column{EntUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EntUsersTable,
	}
)

func init() {
	EntUsersTable.Annotation = &entsql.Annotation{
		Table: "entUsers",
	}
}
