[Client]
	name = "demo"
	proto = "tcp"
	addr = "192.168.11.8:6379"
    idle = 10
    db = 1
    active = 10
    dialTimeout = "1s"
    readTimeout = "3s"
    writeTimeout = "1s"
    idleTimeout = "10s"
